name: Build Custom Kali-T2 Kernel

on:
  workflow_dispatch:
    inputs:
        dry_run:
          description: 'Activate dry run (generate empty .deb)'
          required: true
          type: boolean
          default: true

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ github.event.inputs.dry_run == 'false' }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Prepare system, Kali source repositories, and build kernel
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" kalilinux/kali-rolling:latest /bin/bash -c "cd /workspace && ./build.sh"
      - name: Dry run, Prepare system, Kali source repositories, doesn't build kernel, generate placeholder .deb
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" kalilinux/kali-rolling:latest /bin/bash -c "cd /workspace && ./build_dry_run.sh"


      - name: Create Meta Package
        run: |
          cd ${{ github.workspace }}/build
          sudo chown -R $USER:$USER .

          IMAGE_DEB=$(ls linux-image-*.deb | grep -v "dbg" | head -n 1)
          HEADERS_DEB=$(ls linux-headers-*.deb | head -n 1)
          PACKAGE_IMAGE_NAME=$(dpkg-deb -f "$IMAGE_DEB" Package)
          PACKAGE_HEADERS_NAME=$(dpkg-deb -f "$HEADERS_DEB" Package)
          PACKAGE_VERSION=$(dpkg-deb -f "$IMAGE_DEB" Version)
          META_PACKAGE_NAME="linux-image-kali-t2-amd64"

          mkdir -p deb/DEBIAN
          mkdir -p deb/usr/share/doc/${META_PACKAGE_NAME}
          cp ../.github/copyright deb/usr/share/doc/${META_PACKAGE_NAME}/

          cat <<EOF > deb/usr/share/doc/${META_PACKAGE_NAME}/changelog.Debian
          ${META_PACKAGE_NAME} (${PACKAGE_VERSION}) unstable; urgency=low

            * Initial release with T2 support for Kali Linux.

           -- ${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>  $(date -R)
          EOF
          gzip -n -9 deb/usr/share/doc/${META_PACKAGE_NAME}/changelog.Debian

          cat <<EOF > deb/DEBIAN/control
          Package: ${META_PACKAGE_NAME}
          Version: ${PACKAGE_VERSION}
          Architecture: amd64
          Maintainer: ${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>
          Depends: ${PACKAGE_IMAGE_NAME} (= ${PACKAGE_VERSION}), ${PACKAGE_HEADERS_NAME} (= ${PACKAGE_VERSION})
          Section: kernel
          Priority: optional
          Description: Meta-package for T2 Kernel (Based on Kali)
           This package ensures that the correct Kali-based T2 kernel 
           and headers are installed.
          EOF

          dpkg-deb --build --root-owner-group deb ${META_PACKAGE_NAME}.deb
        env:
          MAINTAINER_NAME: ${{ vars.MAINTAINER_NAME }}
          MAINTAINER_EMAIL: ${{ vars.MAINTAINER_EMAIL }}
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Create Repo
        run: |
          mkdir -p repo-output
          mv build/*.deb repo-output/
          cd repo-output

          apt-ftparchive packages . > Packages
          gzip -k -f Packages

          apt-ftparchive release . > Release
          gpg --batch --yes --armor --local-user "$GPG_SIGNING_EMAIL" --detach-sign -o Release.gpg Release
          gpg --batch --yes --armor --local-user "$GPG_SIGNING_EMAIL" --clearsign -o InRelease Release
          gpg --armor --export "$GPG_SIGNING_EMAIL" > KEY.gpg
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}
      - name: Generate artifact attestation
        id: attest-repo
        uses: actions/attest@v4
        with:
          subject-path: 'repo-output/*'
      - name: Add files to release (dry_run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          RELEASE_NAME=kali-rolling-dry-run
          echo "apt repo for $RELEASE_NAME" > notes.md
          echo "" >> notes.md
          echo "[View GitHub Build Certificate]($BUILD_CERTIFICATE_URL)" >> notes.md
          
          # Delete old release if exists
          gh release delete "$RELEASE_NAME" --yes --cleanup-tag || true

          # Create the new release
          gh release create "$RELEASE_NAME" \
            --title "$RELEASE_NAME" \
            --notes-file notes.md \
            --target ${{ github.ref_name }} \
            --draft=false \
            --prerelease=true
          gh release upload "$RELEASE_NAME" repo-output/* --clobber
        env:
          BUILD_CERTIFICATE_URL: ${{ steps.attest-repo.outputs.attestation-url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add files to release
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          RELEASE_NAME=kali-rolling
          echo "apt repo for $RELEASE_NAME" > notes.md
          echo "" >> notes.md
          echo "[View GitHub Build Certificate]($BUILD_CERTIFICATE_URL)" >> notes.md
          
          gh release upload "$RELEASE_NAME" repo-output/* --clobber
          gh release edit "$RELEASE_NAME" --notes-file notes.md
        env:
          BUILD_CERTIFICATE_URL: ${{ steps.attest-repo.outputs.attestation-url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
